{% set name = "python-engineio" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21e1bcc62f5573a4bb1c805e69915c5a4c5aa953005dde6c2f707c24554c1020

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip

  run:
    - python >=2.7

test:
  imports:
    - engineio
    # - engineio.async_eventlet
    # - engineio.async_gevent
    # - engineio.async_gevent_uwsgi
    # - engineio.async_threading
    - engineio.middleware
    - engineio.packet
    - engineio.payload
    - engineio.server
    - engineio.socket

about:
  home: https://github.com/miguelgrinberg/python-engineio/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Engine.IO server
  doc_url: https://python-engineio.readthedocs.io
  dev_url: https://github.com/miguelgrinberg/python-engineio/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ReimarBauer
    - synapticarbors
