{% set name = "python-engineio" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e97c1189c23923858f5bb6dc47cfcd915005383c3c039ff01c89f2c00d62077

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip

  run:
    - python >=3.5

test:
  imports:
    - engineio
    # - engineio.async_eventlet
    # - engineio.async_gevent
    # - engineio.async_gevent_uwsgi
    # - engineio.async_threading
    - engineio.middleware
    - engineio.packet
    - engineio.payload
    - engineio.server
    - engineio.socket

about:
  home: https://github.com/miguelgrinberg/python-engineio/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Engine.IO server
  doc_url: https://python-engineio.readthedocs.io
  dev_url: https://github.com/miguelgrinberg/python-engineio/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ReimarBauer
    - synapticarbors
