{% set name = "python-engineio" %}
{% set version = "4.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/{{ name }}/python_engineio-{{ version }}.tar.gz
  sha256: 0ad65a743e49b55e333243b95d9b073f2b977a9703e2ce9c6580dab2b4c18cc8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.2
  run:
    - python >={{ python_min}}
    - simple-websocket >=0.10.0

test:
  imports:
    - engineio
    # - engineio.async_eventlet
    # - engineio.async_gevent
    # - engineio.async_gevent_uwsgi
    # - engineio.async_threading
    - engineio.middleware
    - engineio.packet
    - engineio.payload
    - engineio.server
    - engineio.socket
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/miguelgrinberg/python-engineio/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Engine.IO server
  doc_url: https://python-engineio.readthedocs.io
  dev_url: https://github.com/miguelgrinberg/python-engineio/

extra:
  recipe-maintainers:
    - ReimarBauer
    - synapticarbors
