schema_version: 1

context:
  name: python-engineio
  version: "4.13.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/${{ name }}/python_engineio-${{ version }}.tar.gz
  sha256: f9c51a8754d2742ba832c24b46ed425fdd3064356914edd5a1e8ffde76ab7709

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.2
  run:
    - python >=${{ python_min }}
    - simple-websocket >=0.10.0
  run_constraints:
    - requests >=2.21.0
    - websocket-client >=0.54.0
    - aiohttp >=3.4

tests:
  - python:
      imports:
        - engineio
        - engineio.middleware
        - engineio.packet
        - engineio.payload
        - engineio.server
        - engineio.socket
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license_file: LICENSE
  license: MIT
  summary: Engine.IO server
  homepage: https://github.com/miguelgrinberg/python-engineio/
  repository: https://github.com/miguelgrinberg/python-engineio/
  documentation: https://python-engineio.readthedocs.io

extra:
  recipe-maintainers:
    - ReimarBauer
    - synapticarbors
