travis:
  secure:
    BINSTAR_TOKEN: g7+uRf968pMpclLSYb94N1s8yFE3w+XbcnXcw2Kgzr2HaJzHFdCb7dM10jUmq27MCje/TVdVKJLS6DY7RYQm9FWGn0e6Syv6MkznSVHRuhGlhPjNOe2Vqax9Vj/DWJ1swD2je8VnPWGJO/Lun790Rpz1uCmv/CdjuXd9UmVcjq0DmwJVAuaXlrf+cKIQV+Kg8gDYqSE0S5Y0/ibyR2l7nZLONSJwiGX0FZglNZsmtk40TpANlyhVtcBSfcgspcqhwXs/5c4FbaR0fcVRdCa236ZxrQThs2EBzhNon8FkWqftoseEEuOMWl2Y8UM9O83nj8n/djyoB41xM1kxvcQTainkbvwV1GFWKsNWpdSD9CY3/meQHJ9ymw8GkZwNSvs4T3IaUWMlGB6G8bWI/LKgrwA+fx1P2QbCFlbvDwnh+ApjAtjgbqBUwCINJW+AJe0xysgDXfbfLy1SJAILLtDSxyD3XtyUznDEpPnoWuLIs9OYhLXIHm8JMN8YagRzadlSQUJw75IIwfphcEMH4HFsx0CS1Qrl3nLM1EBdnJzElw1c22HyP3X9Uz0AyEmywSOmBmVAljtUWt1Hcth5TamVEuQ0M740Zi1KC6gG8d+qiB3YUHrw0Jgk5e07733xEcsHlQgI8D0UvLdkfsvx90ShVbQPOrdnoBv6kiEDwXH4470=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
